### ISSUE TITLE
Supported backends?

### ISSUE THREAD

**Issue by pwFoo** [dcblogdev/pdo-wrapper#12]
Ist MySQL and sqlite (and PostgreSQL) supported?

**Comment by dcblogdev** [comment]
I'm not sure honestly you can try it by specify on the connection:

```php
$db = Database::get($username, $password, $database, $host = 'localhost', $type = 'sqlite');
```

**Comment by pwFoo** [comment]
Hi @dcblogdev,

found a class which supports MySQL, SQLite and PostgreSQL. Looks like quoting marks are different?

```
If you are using SQLite or PostgreSQL instead of MySQL you will need to change the quoted identifier to the correct character (instead of the MySQL tilde `).

DB::$i = '"';
If you are using PostgreSQL you will also need to set the PostgreSQL marker.

DB::$p = TRUE;
```

Checked source.
- Replace quoting marks https://github.com/Xeoncross/DByte/blob/master/DByte/DB.php#L93
- Default mysql quoting marks used "here":https://github.com/Xeoncross/DByte/blob/master/DByte/DB.php#L105 and "here":https://github.com/Xeoncross/DByte/blob/master/DByte/DB.php#L122

I remind me that also create table syntax (field types) are different between sqlite and mysql.

**Comment by dcblogdev** [comment]
yeah so without some changes this class likely won't work with SQLite and PostgreSQL.

that's a nice class, I'm doing some work with MSSQL soon so will likely adapt this class to work with that too but good to have SQLite and PostgreSQL working ass well.

**Comment by pwFoo** [comment]
I forked and changed the class with minimal testing.
- instance instead of static use
- detect mysql, sqlite and pgsql for auto config the variables.
- instead of string replace quoting marks I changed to variables

Just quick & dirty rewrite for testing.

https://github.com/pwFoo/DByte/blob/master/DByte/DB.php
