### ISSUE TITLE
Need to be able to specify port and charset from outside of class

### ISSUE THREAD

**Issue by khurshid290** [dcblogdev/pdo-wrapper#13]
Hi,
Need to be able to specify port and charset from outside of class when connecting to MySQL server (Database::get(... array options maybe ...)), would be really great if you could implement the feature, that way no need to fork the file and always use the original file with any new version, cheers

**Comment by dcblogdev** [comment]
yes, I'll make the changes

**Comment by dcblogdev** [comment]
what do you think to this:

```php
$options = [
    //required
    'username' => 'root',
    'password' => '',
    'database' => 'temo',
    //optional
    'type' => 'mysql',
    'charset' => 'utf8',
    'host' => 'localhost',
    'port' => '3309'
];

$db = Database::get($options);
```

**Comment by dcblogdev** [comment]
if there is no password and the default are fine then you can keep it as simple as:

```php
$options = [
    'username' => 'root',
    'database' => 'temp'
];
```
