### ISSUE TITLE
update method not using  Where id and subid method 

### ISSUE THREAD

**Issue by mucahidbaris** [dcblogdev/pdo-wrapper#17]
Sql query example 
UPDATE users SET data=:data WHERE id=:id AND subid=:subid

Pdo Wrapper Example with error

$db->update('users', ['data' => 'Editor'], ['id' => $id,':subid'=>$subid]);

**Comment by DizzySquirrel** [comment]
You've got a colon **:** before the 'subid' field key.

Update your where arguments to the following and the query works correctly:
```
$db->update('users', ['data' => 'Editor'], ['id' => $id, 'subid'=>$subid]);
```
